Arguments: 
  /usr/local/Cellar/node/12.8.0/bin/node /usr/local/Cellar/yarn/1.17.3/libexec/bin/yarn.js add flask_wtf

PATH: 
  /Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin

Yarn version: 
  1.17.3

Node version: 
  12.8.0

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/flask_wtf: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:66830:18)
      at Request.self.callback (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:140464:22)
      at Request.emit (events.js:203:13)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:141436:10)
      at Request.emit (events.js:203:13)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:141358:12)
      at Object.onceWrapper (events.js:291:20)
      at IncomingMessage.emit (events.js:208:15)
      at endReadableNT (_stream_readable.js:1168:12)
      at processTicksAndRejections (internal/process/task_queues.js:77:11)

npm manifest: 
  {
    "dependencies": {
      "flask": "^0.2.10"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  
  
  flask@^0.2.10:
    version "0.2.10"
    resolved "https://registry.yarnpkg.com/flask/-/flask-0.2.10.tgz#f5f5a42cfd58a309e37c67c0a39617a819e5e1b7"
    integrity sha1-9fWkLP1YownjfGfAo5YXqBnl4bc=
